// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkrTgxh1D_slbfZC28KS9iMsq7zlLoOlY',
    appId: '1:197394069399:web:2a41d70434d533cbb576d2',
    messagingSenderId: '197394069399',
    projectId: 'campinggearapp-e8103',
    authDomain: 'campinggearapp-e8103.firebaseapp.com',
    storageBucket: 'campinggearapp-e8103.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjoxVX1Qp7mH4guKxJnLfu-yMm4w2XJiM',
    appId: '1:197394069399:android:990aa4a8bad52966b576d2',
    messagingSenderId: '197394069399',
    projectId: 'campinggearapp-e8103',
    storageBucket: 'campinggearapp-e8103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACjCQzk_8AZ9vnrdW9p9VuQgOwtnfDGIQ',
    appId: '1:197394069399:ios:9f3566e0ee7c048fb576d2',
    messagingSenderId: '197394069399',
    projectId: 'campinggearapp-e8103',
    storageBucket: 'campinggearapp-e8103.firebasestorage.app',
    androidClientId:
        '197394069399-5q2nan9uutochf9bsprr819n8qt2nhi2.apps.googleusercontent.com',
    iosClientId:
        '197394069399-ssbs21k268d8n36t6v25rjl19c38s9si.apps.googleusercontent.com',
    iosBundleId: 'com.example.hikingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACjCQzk_8AZ9vnrdW9p9VuQgOwtnfDGIQ',
    appId: '1:197394069399:ios:9f3566e0ee7c048fb576d2',
    messagingSenderId: '197394069399',
    projectId: 'campinggearapp-e8103',
    storageBucket: 'campinggearapp-e8103.firebasestorage.app',
    androidClientId:
        '197394069399-5q2nan9uutochf9bsprr819n8qt2nhi2.apps.googleusercontent.com',
    iosClientId:
        '197394069399-ssbs21k268d8n36t6v25rjl19c38s9si.apps.googleusercontent.com',
    iosBundleId: 'com.example.hikingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkrTgxh1D_slbfZC28KS9iMsq7zlLoOlY',
    appId: '1:197394069399:web:7d624e0dc38a5098b576d2',
    messagingSenderId: '197394069399',
    projectId: 'campinggearapp-e8103',
    authDomain: 'campinggearapp-e8103.firebaseapp.com',
    storageBucket: 'campinggearapp-e8103.firebasestorage.app',
  );
}
